FROM python:3.5

MAINTAINER LabcompTeam

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
        gcc gettext \
        mysql-client libmysqlclient-dev \
        libcairo2-dev \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip
COPY ./requirements/base.pip /requirements/base.pip
COPY ./requirements/development.pip /requirements/development.pip
RUN pip install -r /requirements/development.pip
RUN pip install django-jet