# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Characteristics',
                'verbose_name': 'Characteristic',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'verbose_name': 'Room',
            },
        ),
        migrations.CreateModel(
            name='RoomCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.Characteristic', verbose_name='Characteristic')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.Room', verbose_name='Romm')),
            ],
            options={
                'verbose_name_plural': 'Characteristics of the rooms',
                'verbose_name': 'Characteristic of the room',
            },
        ),
        migrations.CreateModel(
            name='TypeCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Types of characteristics',
                'verbose_name': 'Type of characteristic',
            },
        ),
        migrations.CreateModel(
            name='TypeInfrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('icon', models.CharField(max_length=20, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Types of infrastructures',
                'verbose_name': 'Type of infrastructure',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.TypeInfrastructure', verbose_name='Type of infrastructure'),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.TypeCharacteristic', verbose_name='Type of characteristic'),
        ),
    ]
