# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Característica', 'verbose_name_plural': 'Características'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterModelOptions(
            name='roomcharacteristic',
            options={'verbose_name': 'Característica de la sala', 'verbose_name_plural': 'Características de la sala'},
        ),
        migrations.AlterModelOptions(
            name='typecharacteristic',
            options={'verbose_name': 'Tipo de característica', 'verbose_name_plural': 'Tipos de características'},
        ),
        migrations.AlterModelOptions(
            name='typeinfrastructure',
            options={'verbose_name': 'Tipo de infraestructura', 'verbose_name_plural': 'Tipos de infraestructuras'},
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='icon',
            field=models.CharField(max_length=20, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.TypeCharacteristic', verbose_name='Tipo de característica'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.TypeInfrastructure', verbose_name='Tipo de infraestructura'),
        ),
        migrations.AlterField(
            model_name='roomcharacteristic',
            name='characteristic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.Characteristic', verbose_name='Característica'),
        ),
        migrations.AlterField(
            model_name='roomcharacteristic',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.Room', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='roomcharacteristic',
            name='value',
            field=models.CharField(max_length=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='typecharacteristic',
            name='icon',
            field=models.CharField(max_length=20, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='typecharacteristic',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='typeinfrastructure',
            name='icon',
            field=models.CharField(max_length=20, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='typeinfrastructure',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
