# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity_card',
            field=models.CharField(max_length=8),
        ),
    ]
