# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_subjects', '0001_initial'),
        ('lab_rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourFreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hours Freed',
                'verbose_name': 'Hour Freed',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('type', models.IntegerField(choices=[[1, 'Parcial'], [2, 'Quiz'], [3, 'Preparaduria'], [4, 'Conferencia'], [5, 'Revisión'], [6, 'Clase Recuperativa'], [7, 'Otra']], verbose_name='Type of reservation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
                'verbose_name': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Semester', verbose_name='Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Subject', verbose_name='Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Sections',
                'verbose_name': 'Section',
            },
        ),
        migrations.CreateModel(
            name='StatusReservationHistoric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('status', models.IntegerField(choices=[[1, 'Aprobado'], [2, 'Pendiente'], [3, 'Rechazado'], [4, 'Cancelado']], verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservations.Reservation', verbose_name='Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.IntegerField(choices=[[1, '7:00'], [2, '8:00'], [3, '9:00'], [4, '10:00'], [5, '11:00'], [6, '12:00'], [7, '13:00'], [8, '14:00'], [9, '15:00'], [10, '16:00'], [11, '17:00'], [12, '18:00'], [13, '19:00'], [14, '20:00'], [15, '21:00'], [16, '22:00']], verbose_name='Block')),
                ('day', models.IntegerField(choices=[[1, 'Lunes'], [2, 'Martes'], [3, 'Miércoles'], [4, 'Jueves'], [5, 'Viernes'], [6, 'Sábado'], [7, 'Domingo']], verbose_name='Day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.Room', verbose_name='Room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservations.Section', verbose_name='Section')),
            ],
            options={
                'verbose_name_plural': 'TimeTables',
                'verbose_name': 'TimeTable',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='timetable',
            field=models.ManyToManyField(to='lab_reservations.TimeTable', verbose_name='TimeTable'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='hourfreed',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservations.TimeTable', verbose_name='TimeTable'),
        ),
    ]
