# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourfreed',
            options={'verbose_name': 'Hora liberada', 'verbose_name_plural': 'Horas liberadas'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservación', 'verbose_name_plural': 'Reservaciones'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterField(
            model_name='hourfreed',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='hourfreed',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservations.TimeTable', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Semester', verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Subject', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='timetable',
            field=models.ManyToManyField(to='lab_reservations.TimeTable', verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='type',
            field=models.IntegerField(choices=[[1, 'Parcial'], [2, 'Quiz'], [3, 'Preparaduria'], [4, 'Conferencia'], [5, 'Revisión'], [6, 'Clase Recuperativa'], [7, 'Otra']], verbose_name='Tipo de reservación'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Semester', verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Subject', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='statusreservationhistoric',
            name='end_date',
            field=models.DateTimeField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='statusreservationhistoric',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservations.Reservation', verbose_name='Reservación'),
        ),
        migrations.AlterField(
            model_name='statusreservationhistoric',
            name='start_date',
            field=models.DateTimeField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='block',
            field=models.IntegerField(choices=[[1, '7:00'], [2, '8:00'], [3, '9:00'], [4, '10:00'], [5, '11:00'], [6, '12:00'], [7, '13:00'], [8, '14:00'], [9, '15:00'], [10, '16:00'], [11, '17:00'], [12, '18:00'], [13, '19:00'], [14, '20:00'], [15, '21:00'], [16, '22:00']], verbose_name='Bloque'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(choices=[[1, 'Lunes'], [2, 'Martes'], [3, 'Miércoles'], [4, 'Jueves'], [5, 'Viernes'], [6, 'Sábado'], [7, 'Domingo']], verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_rooms.Room', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_reservations.Section', verbose_name='Sección'),
        ),
    ]
