# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reservations', '0002_alter_by_locale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='block',
            new_name='block_start',
        ),
        migrations.AddField(
            model_name='timetable',
            name='block_end',
            field=models.IntegerField(choices=[[1, '7:00'], [2, '8:00'], [3, '9:00'], [4, '10:00'], [5, '11:00'], [6, '12:00'], [7, '13:00'], [8, '14:00'], [9, '15:00'], [10, '16:00'], [11, '17:00'], [12, '18:00'], [13, '19:00'], [14, '20:00'], [15, '21:00'], [16, '22:00']], default=None, verbose_name='block'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.IntegerField(choices=[[0, 'Lunes'], [1, 'Martes'], [2, 'Miércoles'], [3, 'Jueves'], [4, 'Viernes'], [5, 'Sábado'], [6, 'Domingo']], verbose_name='day'),
        ),
    ]
