# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reservations', '0004_auto_20161027_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreservationhistoric',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
    ]
