# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_reservations', '0006_remove_reservation_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
