# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 18:25
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='reservationpermission',
            options={'verbose_name': 'Permiso de Reservación', 'verbose_name_plural': 'Permisos de Reservación'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semestre', 'verbose_name_plural': 'Semestres'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=colorful.fields.RGBColorField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='rooms',
            field=models.ManyToManyField(to='lab_rooms.Room', verbose_name='Salas'),
        ),
        migrations.AlterField(
            model_name='department',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuarios'),
        ),
        migrations.AlterField(
            model_name='reservationpermission',
            name='biweekly_limit',
            field=models.IntegerField(default=0, verbose_name='Límite quincenal'),
        ),
        migrations.AlterField(
            model_name='reservationpermission',
            name='block_limit',
            field=models.IntegerField(default=0, verbose_name='Límite de bloque'),
        ),
        migrations.AlterField(
            model_name='reservationpermission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='reservationpermission',
            name='monthly_limit',
            field=models.IntegerField(default=0, verbose_name='Límite mensual'),
        ),
        migrations.AlterField(
            model_name='reservationpermission',
            name='weekly_limit',
            field=models.IntegerField(default=0, verbose_name='Límite semanal'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='present',
            field=models.BooleanField(verbose_name='Actual'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_subjects.Department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
